# Configuração do MKDocs para TI OSN System
site_name: TI OSN System - Documentação Oficial
site_description: Documentação completa do Sistema de Gerenciamento TI OSN - Versão 2.0 (Segurança Enterprise)
site_author: Oézios Normando - Equipe TI OSN
site_url: http://192.168.1.86:5000/docs/

# Tema
theme:
  name: readthedocs
  locale: pt_BR

# Plugins
plugins:
  - search

# Navegação
nav:
  - Início: index.md
  - Guia do Usuário:
    - Visão Geral: user-guide/overview.md
    - Segurança: user-guide/security.md
    - Atividades & Projetos: user-guide/tasks.md
    - Notificações Programadas: user-guide/reminders.md
    - Tickets & Suporte: user-guide/chamados.md
    - Gestão de Ativos: user-guide/equipment.md
    - Base de Conhecimento: user-guide/tutorials.md
    - Equipamentos: user-guide/equipment.md
    - Dashboard: user-guide/dashboard.md
    - Sistema RFID: user-guide/rfid.md
    - Avaliação de Satisfação: user-guide/satisfaction.md
    - Certificações: user-guide/certifications.md
    - Performance: user-guide/performance.md
  - Guia do Administrador:
    - Gerenciamento de Segurança: admin-guide/security-admin.md
    - Equipamentos: admin-guide/equipment-admin.md
    - Performance: admin-guide/performance-admin.md
    - RFID: admin-guide/rfid-admin.md
    - Satisfação: admin-guide/satisfaction-admin.md
    - Certificações: admin-guide/certifications-admin.md
  - Guia do Desenvolvedor:
    - Implementação de Segurança: dev-guide/security-implementation.md

# Configurações de Markdown
markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - meta
  - tables
  - toc:
      permalink: true

# CSS personalizado
extra_css:
  - stylesheets/extra.css

# JavaScript personalizado
extra_javascript:
  - javascripts/extra.js

# Configurações adicionais
extra:
  generator: false

# Configurações de build
use_directory_urls: true
strict: false