"""Add Chamado model

Revision ID: 129157f75b14
Revises: dd49f2c40d24
Create Date: 2025-05-27 12:13:15.086533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129157f75b14'
down_revision = 'dd49f2c40d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chamado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('prioridade', sa.String(length=50), nullable=False),
    sa.Column('data_abertura', sa.DateTime(), nullable=False),
    sa.Column('data_ultima_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('data_fechamento', sa.DateTime(), nullable=True),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_ti_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['responsavel_ti_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['sector.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chamado')
    # ### end Alembic commands ###
