"""Adiciona modelos de tutorial, imagens, comentários, feedback e visualizações

Revision ID: 85b6155f9999
Revises: d5ed9f9f0bd7
Create Date: 2025-06-25 15:13:38.962367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b6155f9999'
down_revision = 'd5ed9f9f0bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutorial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentario_tutorial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutorial_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('chamado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamado.id'], ),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorial.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_tutorial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutorial_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('util', sa.Boolean(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorial.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutorial_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutorial_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorial.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visualizacao_tutorial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutorial_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorial.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visualizacao_tutorial')
    op.drop_table('tutorial_image')
    op.drop_table('feedback_tutorial')
    op.drop_table('comentario_tutorial')
    op.drop_table('tutorial')
    # ### end Alembic commands ###
