"""Adicionar campos para melhorias do sistema

Revision ID: 8d56434892fd
Revises: 202eb034c231
Create Date: 2025-10-16 09:56:00.637679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d56434892fd'
down_revision = '202eb034c231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_sla_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('sla_hours', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('priority')
    )
    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('advance_hours', sa.Integer(), nullable=True),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('browser_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_certification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('tutorials_created', sa.Integer(), nullable=True),
    sa.Column('tutorials_approved', sa.Integer(), nullable=True),
    sa.Column('awarded_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('satisfaction_survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamado_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('speed_rating', sa.Integer(), nullable=True),
    sa.Column('quality_rating', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamado.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipment_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rfid_tag', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('return_alert_sent', sa.Boolean(), nullable=True))

    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('escalation_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_escalation', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('escalated_to', sa.String(length=100), nullable=True))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sla_deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('notification_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('tutorial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('pontos_certificacao', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('aprovado_por_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data_aprovacao', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['aprovado_por_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorial', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('data_aprovacao')
        batch_op.drop_column('aprovado_por_id')
        batch_op.drop_column('pontos_certificacao')
        batch_op.drop_column('status')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('notification_sent')
        batch_op.drop_column('sla_deadline')
        batch_op.drop_column('priority')

    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.drop_column('escalated_to')
        batch_op.drop_column('last_escalation')
        batch_op.drop_column('escalation_level')

    with op.batch_alter_table('equipment_request', schema=None) as batch_op:
        batch_op.drop_column('return_alert_sent')
        batch_op.drop_column('last_location')
        batch_op.drop_column('rfid_tag')

    op.drop_table('satisfaction_survey')
    op.drop_table('user_certification')
    op.drop_table('notification_settings')
    op.drop_table('task_sla_config')
    # ### end Alembic commands ###
