"""initial

Revision ID: 99c62be90766
Revises: aa0bcd2a67ee
Create Date: 2025-08-20 10:51:21.849158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c62be90766'
down_revision = 'aa0bcd2a67ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chamado')
    op.drop_table('task')
    op.drop_table('tutorial')
    op.drop_table('user')
    op.drop_table('reminder')
    op.drop_table('sector')
    op.drop_table('feedback_tutorial')
    op.drop_table('comentario_chamado')
    op.drop_table('visualizacao_tutorial')
    op.drop_table('comentario_tutorial')
    op.drop_table('equipment_request')
    op.drop_table('tutorial_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutorial_image',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tutorial_id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('upload_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorial.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('patrimony', sa.VARCHAR(length=50), nullable=True),
    sa.Column('delivery_date', sa.DATE(), nullable=True),
    sa.Column('return_date', sa.DATE(), nullable=True),
    sa.Column('conference_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('observations', sa.TEXT(), nullable=True),
    sa.Column('requester_id', sa.INTEGER(), nullable=False),
    sa.Column('received_by_id', sa.INTEGER(), nullable=True),
    sa.Column('approved_by_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('request_date', sa.DATETIME(), nullable=False),
    sa.Column('approval_date', sa.DATETIME(), nullable=True),
    sa.Column('equipment_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('destination_sector', sa.VARCHAR(length=100), nullable=True),
    sa.Column('request_reason', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['received_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentario_tutorial',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tutorial_id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.Column('texto', sa.TEXT(), nullable=False),
    sa.Column('data_criacao', sa.DATETIME(), nullable=True),
    sa.Column('chamado_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamado.id'], ),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorial.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visualizacao_tutorial',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tutorial_id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.Column('data', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorial.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentario_chamado',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chamado_id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.Column('texto', sa.TEXT(), nullable=False),
    sa.Column('data_criacao', sa.DATETIME(), nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamado.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_tutorial',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tutorial_id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.Column('util', sa.BOOLEAN(), nullable=False),
    sa.Column('data', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorial.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sector',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('reminder',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('due_date', sa.DATE(), nullable=False),
    sa.Column('responsible', sa.VARCHAR(length=100), nullable=False),
    sa.Column('frequency', sa.VARCHAR(length=20), nullable=True),
    sa.Column('notified', sa.BOOLEAN(), nullable=True),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.Column('sector_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('pause_until', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.Column('is_ti', sa.BOOLEAN(), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.Column('sector_id', sa.INTEGER(), nullable=True),
    sa.Column('reset_token', sa.VARCHAR(length=100), nullable=True),
    sa.Column('reset_token_expiry', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tutorial',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=150), nullable=False),
    sa.Column('conteudo', sa.TEXT(), nullable=False),
    sa.Column('data_criacao', sa.DATETIME(), nullable=False),
    sa.Column('autor_id', sa.INTEGER(), nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('responsible', sa.VARCHAR(length=100), nullable=False),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.Column('sector_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chamado',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=120), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('prioridade', sa.VARCHAR(length=50), nullable=False),
    sa.Column('data_abertura', sa.DATETIME(), nullable=False),
    sa.Column('data_ultima_atualizacao', sa.DATETIME(), nullable=True),
    sa.Column('data_fechamento', sa.DATETIME(), nullable=True),
    sa.Column('solicitante_id', sa.INTEGER(), nullable=False),
    sa.Column('setor_id', sa.INTEGER(), nullable=False),
    sa.Column('responsavel_ti_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['responsavel_ti_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['sector.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
