"""Sincronizar modelos com banco de dados

Revision ID: a04cc84a5342
Revises: b91b0d7d62b4
Create Date: 2025-09-05 11:20:41.292049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a04cc84a5342'
down_revision = 'b91b0d7d62b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sla_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prioridade', sa.String(length=50), nullable=False),
    sa.Column('tempo_resposta_horas', sa.Integer(), nullable=False),
    sa.Column('tempo_resolucao_horas', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prioridade')
    )
    with op.batch_alter_table('chamado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prazo_sla', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data_primeira_resposta', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sla_cumprido', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('tempo_resposta_horas', sa.Float(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'sector', ['sector_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('chamado', schema=None) as batch_op:
        batch_op.drop_column('tempo_resposta_horas')
        batch_op.drop_column('sla_cumprido')
        batch_op.drop_column('data_primeira_resposta')
        batch_op.drop_column('prazo_sla')

    op.drop_table('sla_config')
    # ### end Alembic commands ###
