"""Adicionar campos de SLA ao sistema de chamados

Revision ID: b91b0d7d62b4
Revises: a861e2bfb112
Create Date: 2025-09-05 12:35:36.010970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b91b0d7d62b4'
down_revision = 'a861e2bfb112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sla_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prioridade', sa.String(length=50), nullable=False),
    sa.Column('tempo_resposta_horas', sa.Integer(), nullable=False),
    sa.Column('tempo_resolucao_horas', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prioridade')
    )
    with op.batch_alter_table('chamado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prazo_sla', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data_primeira_resposta', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sla_cumprido', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('tempo_resposta_horas', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamado', schema=None) as batch_op:
        batch_op.drop_column('tempo_resposta_horas')
        batch_op.drop_column('sla_cumprido')
        batch_op.drop_column('data_primeira_resposta')
        batch_op.drop_column('prazo_sla')

    op.drop_table('sla_config')
    # ### end Alembic commands ###
