"""Adiciona campo is_ti ao modelo User

Revision ID: c3d9d5e97793
Revises: 3c859fca7b64
Create Date: 2025-05-27 16:59:29.908690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d9d5e97793'
down_revision = '3c859fca7b64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ti', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_ti')

    # ### end Alembic commands ###
