"""Add sector_id to User model

Revision ID: d5ed9f9f0bd7
Revises: c3d9d5e97793
Create Date: 2025-06-02 06:59:18.034093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ed9f9f0bd7'
down_revision = 'c3d9d5e97793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.add_column(sa.Column('sector_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_sector', 'sector', ['sector_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_constraint('fk_user_sector', type_='foreignkey')
        batch_op.drop_column('sector_id')

    # ### end Alembic commands ###
